resolver: lts-13.22

packages:
- .
# - prelude
# - lorentz-contracts
# - indigo

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- show-type-0.1.1
- constraints-0.11.2@sha256:d028005d93f891b48b61ff0c82c6f868859eb728010dea3e355b0c55d0f57cf9
- pretty-terminal-0.1.0.0@sha256:e9135d86ebb2a8e3aaf5a79088de4628dbd49988388e0fbfc26c5ecb3c399ad9
- type-equality-1@sha256:aeb9c44abf5d2edf52caff114a7da565d8328fa84bbe194828e4355ea85bf5b3

- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    7100194bf49e4fd7425545fadf349ae0e868fa7c # master
  subdirs:
    - .
    - lorentz-contracts
    - prelude
    - indigo

nix:
  shell-file: shell.nix
